### PR TITLE
fix text and example being out of sync

### PR DESCRIPTION
**Pull request by sseering**

### CODE REVIEW

**Comment by thegedge** [comment]
Ahhh, thanks for the fix. I know your PR came in first, but I happened to open and view https://github.com/nushell/book/pull/92 first and merged it, so we no longer need this one 😞

**Comment by mhmdanas** [comment]
Ah, I didn't notice this PR as I was in a hurry. Sorry @sseering.

**Comment by mhmdanas** [comment]
BTW, I read the other translations, and although I know neither Spanish nor Japanese, it seems the commands there use 4kb instead of 1kb, so I think this PR is better than mine.

**Comment by thegedge** [comment]
Ah, perhaps. We should consider coming back and doing a consistency pass in the near future. Having the exact same text, outputs, etc will make it far easier to translate in the future.

**Comment by mhmdanas** [comment]
How about I open an issue to track this?

**Comment by thegedge** [comment]
An issue sounds great!

> IMHO, I think it would be good if we can store any commands, outputs, etc. in separate files that act as the sources of truth. We could then somehow use them in the markdown files. I don't know if that's possible, though.

We've been talking about an interactive walkthrough built into the shell itself, which we could more easily build in a way that ensures nothing goes stale 🙂

**Comment by mhmdanas** [comment]
Opened #94.

**Pull request closed without merging**
