### PR TITLE
update introduction to latest nu

### LINKED ISSUE #68: Book introduction out of date
See https://github.com/nushell/nushell/issues/1679

### PR DESCRIPTION
**Pull request by jzaefferer**
Fixes #68 

Somehow the rendered markdown is worse, which I don't understand:

Screen Shot 2020-05-05 at 21 30 06

In my editor its fine, in my editors' markdown preview its fine, but when rendered by Jekyll (or here in the GitHub diff), the header row doesn't align with the rest anymore.

Any idea what's going on there?

### CODE REVIEW

**Comment by jonathandturner** [comment]
hmm, so I looked at the examples

It seems like there are 5 horizontal lines, but the space in the cells is only 4 (including the number or `#`)

Are you copying from what Nu outputs?  I wonder where it might be coming from

**Comment by sebastian-xyz** [comment]
@jzaefferer I tested it on my machine and the rendering looks good. Since we use local fonts for displaying code I guess you just need to install one of the supported fonts on your machine or we can add more fonts.

We currently use `Consolas, Menlo, Monaco, Hack, Roboto Mono, Droid Sans Mono, Liberation Mono, DejaVu Sans Mono, monospace` where `Consolas` and `Monaco` are the default monospace fonts on Windows and macOS. We tried to include the most common ones for Linux but there are just too many to include them all.

I think `monospace` is not sufficient for proper box drawing. It's just the fallback font.

**Comment by jzaefferer** [comment]
> Are you copying from what Nu outputs? I wonder where it might be coming from

@jonathandturner yeah, I copied the nu output from iTerm2 and pasted it in VS Code in the markdown file. There it still looks fine.

> I think monospace is not sufficient for proper box drawing. It's just the fallback font.

As far as I can tell, in the browser its being rendered with Consolas - that's available on my machine.

PS: nu's own markdown renderer (`open en/introduction.md | save intro.html`) doesn't convert the code blocks, so that test is useless

**Comment by jzaefferer** [comment]
Something weird is going on here:

Screen Shot 2020-05-06 at 13 56 02

There's two spaces rendered after the `#`, indicated by the gray centered dots. Yet those are missing around the "pipe" between the `0` and `404.html`. No (regular) spaces around `type`, but they exist on the left side of the previous pipe.

Seems like there's a mix of whitespace character in use, and some (html) renderers mess those up.

**Comment by jonathandturner** [comment]
@jzaefferer interesting. I wonder if that's an issue with the table renderer we use in Nu itself.

**Comment by jonathandturner** [comment]
I think I see why this is happening.  If you do a long `ls` then it adds some extra space that wouldn't be there for small directories.

I say let's land it and fix where necessary. There are a lot of good updates here.

**Pull request merged**
