### PR TITLE
docs: fix missing backtick in coming_from_bash.md

### PR DESCRIPTION
**Pull request by IgorMinar**

### CODE REVIEW

**Comment by jonathandturner** [comment]
I noticed that github's markdown rendering is different than other markdown renderers.

The official books version of this looks a bit better:

https://www.nushell.sh/book/en/coming_from_bash.html

**Comment by IgorMinar** [comment]
the website seems to be more forgiving, but you likely don't want to rely on that.

**Comment by jonathandturner** [comment]
@IgorMinar the example here is the pipeline `ls | where type == Dir`. We're working on aliases to make it smaller :) but basically the structured output from `ls` flows through the `where` command.

**Comment by IgorMinar** [comment]
OMG, I see!

yeah, that is unfortunately long :-) 

I'll close this PR

**Pull request closed without merging**
